services:
  server:
    container_name: Real_time_Voice_Phishing_Detection
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../NLU:/NLU
    env_file:
      - .env
    environment:
      - DEBUG=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
